spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpashop?serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
  # show_sql: true
      format_sql: true
  devtools:
    restart:
      enabled: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hiberante.type: trace
server:
  port: 3005